# Ref: https://hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/
# Ref: https://gist.github.com/andreyvit/2921703

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
# bind 'C-a C-a' to type 'C-a'
bind C-a send-prefix

set-window-option -g mode-keys vi

# reduce leader time for responsiveness (default is 500 ms)
set -s escape-time 90

# split panes using | and - and _
bind | split-window -h
bind - split-window -v
bind _ split-window -v
unbind '"'
unbind %

# increase scrollback history
set -g history-limit 100000

# enable mouse mode for easier pane and window management
set -g mouse on

# detach: allow C-a C-d in addition to C-a d
bind C-d detach

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.config/tmux/tmux.conf

bind Space next-window
# Tab movement bindings without the C-a prefix
bind -n M-Left previous-window
bind -n M-Right next-window
bind -n M-S-Left swap-window -t -1 \; previous-window
bind -n M-S-Right swap-window -t +1 \; next-window
# And tmux's defaults provide emacs-style: n(ext) and p(previous)

# capital N for next window with an alert
bind N next-window -a

# Allow C-a C-[ in addition to C-a [
bind C-[ copy-mode

# extra binding for detach (C-a C-d in addition to C-a d)
bind C-d detach

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=red'
set -g status-bg gray15

# set -g status-left '#h '

set -g status-right-style 'fg=black bg=yellow'
set -g status-right ' "#{=22:pane_title}" %Y-%m-%d %H:%M'
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50

setw -g window-status-current-style 'fg=black bg=red'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=red bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '

# show window tabs with activity in yellow
setw -g monitor-activity on
# setw -g window-status-activity-style 'fg=black bg=green italics'
setw -g window-status-activity-style 'bg=black fg=green italics'
# setw -g window-status-activity-style 'italics'

setw -g window-status-bell-style 'fg=yellow bg=red bold'
